---
docker_workspace: test
docker_application_name: nginx
docker_auto_startup: n
docker_create_volumes_main_directory: y
docker_registry_private: n
docker_container_name: nginx
docker_image_name: nginx
docker_image_tag: latest
docker_ports:
  - "8080:8080"
docker_environment_variables:
  - name: VARIABLE
    value: VALUE
docker_extra_hosts:
  - "HOST:IP"
docker_commands:
  - command1=command1
  - --command2 command2
  - --command3=command3
docker_entrypoints:
  - entrypoint-first
  - entrypoint-second
