---
- name: configure required packages
  include_tasks: packages.yml

- name: configure docker registry
  include_tasks: registry.yml

- name: configure docker application
  include_tasks: docker-application.yml

- name: configure system unit
  include_tasks: system-unit.yml
  when: docker_create_system_unit == 'y'

- name: cleanup
  include_tasks: cleanup.yml
