---
- name: add the docker oficial repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: enable docker-ce oficial repository
  ini_file:
    path: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-stable'
    option: enabled
    value: 1

- name: install packages
  package:
    name: ['iptables-services']
    state: present

- name: enable iptables
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  loop: 
    - iptables

- name: install packages
  package:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'python3-pip', 'curl', 'wget', 'unzip', 'bind-utils']
    state: present

- name: check that the docker.sock exists
  stat:
    path: /var/run/docker.sock
  register: docker_sock_stat_result

- name: make sure docker service is running
  systemd:
    state: started
    name: docker
  when: not docker_sock_stat_result.stat.exists

- name: install python libraries
  pip:
    name: ['docker', 'docker-compose']
    state: present
