---
- name: login into docker registry
  docker_login:
    registry_url: '{{ docker_registry_url }}'
    username: '{{ docker_registry_username }}'
    password: '{{ docker_registry_password }}'
  when: docker_registry_private == 'y'
