---
docker_workspace: test
docker_application_name: nginx
docker_auto_startup: n
docker_registry_private: n
docker_container_name: nginx
docker_image_name: nginx
docker_image_tag: latest
docker_ports:
  - "8080:8080"
docker_volumes:
  - type: volume
    source: test
    destination: /test
    directory: true
  - type: volume
    source: test1
    destination: /test1
    directory: true
    create: "n"
  - type: bind
    source: /root/test
    destination: ~/test
    directory: true
    external: true
  - type: bind
    source: /root
    destination: ~/test.txt
    directory: false
    external: true
    file: test.txt
docker_environment_variables:
  - name: VARIABLE
    value: VALUE
docker_extra_hosts:
  - "HOST:IP"
docker_commands:
  - command1=command1
  - --command2 command2
  - --command3=command3
docker_entrypoints:
  - entrypoint-first
  - entrypoint-second
docker_networks:
  - mode: default
    name: network1
  - mode: create
    name: network2
  - mode: join
    name: network3
  - mode: join
    name: network4
    external: 'false'
docker_labels:
  - "traefik.enable=true"
  - "traefik.http.routers.globalErrorsHandler.entrypoints=http"
  - "traefik.http.routers.globalErrorsHandler.rule=HostRegexp(`{host:.+}`)"
  - "traefik.http.routers.globalErrorsHandler-secure.entrypoints=https"
