# name: Test

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
      - run: |
          apk add --update alpine-sdk
          apk add --no-cache --virtual .build-deps g++ python3 python3-dev py3-pip libffi-dev openssl-dev
        name: install dependencies
